apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadtijz2891-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadtijz2891-tenant-component
    app.kubernetes.io/part-of: loadtijz2891-tenant-app
  name: loadtijz2891-tenant-component
  namespace: loadtijz2891-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadtijz2891-tenant-component
    weight: null
status: {}
